### ISSUE TITLE
[Bug]: Unable to get parent item properties at backlinks.

### ISSUE THREAD

**Issue by barqui** [realm/realm-dart#1018]
### What happened?

Can not get parent properties. 

When get parent's property using backlink, realm fire column does not exist exception on child item.
like `Unhandled Exception: RealmException: Error getting property ChildModel.name Error: RealmException: Error code: 8 . Message: Column does not exist`

### Repro steps

run attached codes.

### Version

0.7.0rc

### What Realm SDK flavor are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Flutter 3.3.7 ipadOS 16 android 12

### Code snippets

```
void main() {
  final realm =
      Realm(Configuration.inMemory([ParentModel.schema, ChildModel.schema]));

  final child = ChildModel(Uuid.v4(), 'key', 'name');

  realm.write(() {
    final parent = ParentModel(Uuid.v4(), 'pkey', 'pname');
    realm.add(child);
    realm.add(parent);
    parent.children.add(child);
  });

  print(child.name);
  print(child.parents.first.name);
}

@RealmModel()
class $ParentModel {
  @PrimaryKey()
  late Uuid uniqueId;

  @Indexed()
  late String key;

  @Indexed()
  late String name;

  late List<$ChildModel> children;
}

@RealmModel()
class $ChildModel {
  @PrimaryKey()
  late Uuid uniqueId;

  @Indexed()
  late String key;

  @Indexed()
  late String name;

  @Backlink(#children)
  late Iterable<$ParentModel> parents;
}

```

### Stacktrace of the exception/crash you're getting

```shell
E/flutter (27850): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RealmException: Error getting property ChildModel.name Error: RealmException: Error code: 8 . Message: Column does not exist
E/flutter (27850): Exception backtrace:
E/flutter (27850): <backtrace not supported on this platform>
E/flutter (27850): #0      RealmCoreAccessor.get
package:realm/src/realm_object.dart:188
E/flutter (27850): #1      RealmObjectBase.get
package:realm/src/realm_object.dart:272
E/flutter (27850): #2      ParentModel.name
package:realm_test/realm.g.dart:37
E/flutter (27850): #3      main
package:realm_test/realm.dart:19
E/flutter (27850): #4      _runMain.<anonymous closure> (dart:ui/hooks.dart:134:23)
E/flutter (27850): #5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter (27850): #6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (27850):
```

**Comment by nielsenko** [comment]
I have PR #1020 ready with a fix. Sorry for the inconvenience.

**Comment by barqui** [comment]
@nielsenko 
Did you have approximate update date for fix this? 
I'm big fan of back link feature and I want to test it asap.

**Comment by nielsenko** [comment]
Hi @barqui 
We are awaiting an important fix for iOS from realm-core before cutting a release. I'm told it should happen today.
