### ISSUE TITLE
Realm generator failure

### ISSUE THREAD

**Issue by ab-rdarts** [realm/realm-dart#1285]
### What happened?

Realm generate gives unexpected error for mobx stores:

```
[SEVERE] realm:realm_generator on lib/presentation/subscription_page/subscription_store.dart:

type 'ClassTypeAliasImpl' is not a subtype of type 'ClassDeclaration' in type cast
#0      ClassElementEx.declarationAstNode (package:realm_generator/src/class_element_ex.dart:61:84)
#1      ElementEx.declarationAstNode (package:realm_generator/src/element.dart:71:43)
#2      ElementEx._annotationsInfoOfExact (package:realm_generator/src/element.dart:79:18)
#3      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:554:14)
#4      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#6      new List.of (dart:core-patch/array_patch.dart:47:28)
#7      Iterable.toList (dart:core/iterable.dart:494:7)
#8      ElementEx.annotationInfoOfExact (package:realm_generator/src/element.dart:89:58)
#9      ClassElementEx.realmModelInfo (package:realm_generator/src/class_element_ex.dart:63:42)
#10     ClassElementEx.realmInfo (package:realm_generator/src/class_element_ex.dart:67:25)
#11     _extension#0.realmInfo.<anonymous closure> (package:realm_generator/src/realm_object_generator.dart:71:58)
#12     MappedIterator.moveNext (dart:_internal/iterable.dart:393:20)
#13     WhereIterator.moveNext (dart:_internal/iterable.dart:440:22)
#14     CastIterator.moveNext (dart:_internal/cast.dart:61:30)
#15     ExpandIterator.moveNext (dart:_internal/iterable.dart:479:21)
#16     Iterable.join (dart:core/iterable.dart:444:19)
#17     RealmObjectGenerator.generate.<anonymous closure>.<anonymous closure> (package:realm_generator/src/realm_object_generator.dart:61:69)
#18     _rootRun (dart:async/zone.dart:1399:13)
#19     _CustomZone.run (dart:async/zone.dart:1301:19)
#20     _runZoned (dart:async/zone.dart:1804:10)
#21     runZonedGuarded (dart:async/zone.dart:1792:12)
#22     scopeSession (package:realm_generator/src/session.dart:44:16)
#23     RealmObjectGenerator.generate.<anonymous closure> (package:realm_generator/src/realm_object_generator.dart:59:16)
<asynchronous suspension>
#24     measure.<anonymous closure> (package:realm_generator/src/measure.dart:50:18)
<asynchronous suspension>
#25     measure (package:realm_generator/src/measure.dart:47:7)
<asynchronous suspension>
#26     RealmObjectGenerator.generate (package:realm_generator/src/realm_object_generator.dart:56:12)
<asynchronous suspension>
#27     _generate (package:source_gen/src/builder.dart:355:23)
<asynchronous suspension>
#28     Stream.toList.<anonymous closure> (dart:async/stream.dart:1343:9)
<asynchronous suspension>


in: package:insects/presentation/subscription_page/subscription_store.dart:5:7
  ╷
5 │ class SubscriptionStore = _SubscriptionStore with _$SubscriptionStore;
  │       ^^^^^^^^^^^^^^^^^
  ╵
Unexpected error. Please open an issue on: https://github.com/realm/realm-dart
```

### Repro steps

I think it's just enough to add realm and mobx store to project

### Version

dart 3.0.0, flutter 3.10.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

OSX 12.5

**Comment by ab-rdarts** [comment]
It works by excluding mobx store files in the build.yaml
