### ISSUE TITLE
realm conflict with l10n dependencies. 

### ISSUE THREAD

**Issue by Justincyz** [realm/realm-dart#1645]
### What happened?

The bug I am facing is behaving very similarly to (https://github.com/realm/realm-dart/issues/1317). But found out they are two different root causes. After run 'dart run build_runner build --delete-conflicting-outputs'
I got this output.
Unhandled exception:
Bad state: Unable to generate package graph, no `/Users/justin/Desktop/flutter-project/flutter project/RG-LINK/.dart_tool/flutter_gen/pubspec.yaml` found.
#0      _pubspecForPath (package:build_runner_core/src/package_graph/package_graph.dart:268:5)
#1      _parsePackageDependencies (package:build_runner_core/src/package_graph/package_graph.dart:242:21)
#2      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:120:33)
<asynchronous suspension>
#3      main (file:///Users/justinchen/.pub-cache/hosted/pub.dev/build_runner-2.4.9/bin/build_runner.dart:27:30) '''

Then I did some research on Google and found this article (https://github.com/dart-lang/build/issues/2835).  Basically, the conflict is because I am using International dependency (l10n package). And the 
<img width="608" alt="截屏2024-04-24 13 52 43" src="https://github.com/realm/realm-dart/assets/30378016/5730a85e-e8d3-41f1-84f6-58123003ec1a">
'generate' field must be true to enable translation to happen. In order to fix realm issue, I currently turn this field to false.  

### Repro steps

just following the setup instructions but nothing happends. 
```
justin@YC-Macbook-Pro-16  % dart run realm generate     
Building package executable... (1.6s)
Built realm:realm.
```

### Version

latest

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

MacOS

**Comment by nielsenko** [comment]
Why do think this is caused by realm-dart?

When running `dart run realm generate` you are essentially calling `dart run build_runnner build --delete-conflicting-outputs`.

**Comment by nielsenko** [comment]
What does dart --version output?

Also, could you try option 2 from: https://github.com/dart-lang/sdk/issues/53696#issuecomment-1833593144
