### ISSUE TITLE
Error librealm_dart.so

### ISSUE THREAD

**Issue by AhmadFikriAS** [realm/realm-dart#1689]
### What happened?

After I updated to version 2.3.0, I got the error Realm error : could not open librealm_dart.so Tried : - "librealm_dart.so" hint : did you forget to add a dependency on the realm package?  

### Repro steps

Got error when flutter run. 

<img width="365" alt="image" src="https://github.com/realm/realm-dart/assets/43110908/134b7c53-688a-4d03-a7c8-2cea48fe8b01">

### Version

3.4.1/3.22.1

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Android

### Stacktrace of the exception/crash you're getting

```shell
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following RealmError was thrown building Splash(state: _SplashState#14652):
Realm error : Could not open librealm_dart.so. Tried:
- "librealm_dart.so"
Hint: Did you forget to add a dependency on the realm package?

The relevant error-causing widget was:
  Splash Splash:file:///D:/Programming/ProjectFlutter/parkways_onstreet_v2/lib/main.dart:72:27

When the exception was thrown, this was the stack:
#0      _openRealmLib.throwError (package:realm_dart/src/init.dart:71:5)
#1      _openRealmLib (package:realm_dart/src/init.dart:84:29)
#2      initRealm (package:realm_dart/src/init.dart:120:24)
#3      _realmLib.<anonymous closure> (package:realm_dart/src/native/realm_core.dart:47:31)
#4      _realmLib (package:realm_dart/src/native/realm_core.dart:55:2)
#5      _realmLib (package:realm_dart/src/native/realm_core.dart)
#6      new _RealmCore (package:realm_dart/src/native/realm_core.dart:104:5)
#7      realmCore (package:realm_dart/src/native/realm_core.dart:81:24)
#8      realmCore (package:realm_dart/src/native/realm_core.dart)
#9      Configuration.defaultStoragePath (package:realm_dart/src/configuration.dart:85:14)
#10     Configuration.defaultRealmPath (package:realm_dart/src/configuration.dart:95:47)
#11     Configuration.defaultRealmPath (package:realm_dart/src/configuration.dart)
#12     Configuration._defaultPath (package:realm_dart/src/configuration.dart:109:44)
#13     new Configuration._ (package:realm_dart/src/configuration.dart:105:50)
#14     new LocalConfiguration._ (package:realm_dart/src/configuration.dart:257:14)
#15     Configuration.local (package:realm_dart/src/configuration.dart:154:26)
#16     new RealmDBDevice._ (package:parkways_onstreet_v2/core/domain/database/checkdevice_db.dart:6:32)
#17     new RealmDBDevice (package:parkways_onstreet_v2/core/domain/database/checkdevice_db.dart:13:58)
#18     new CheckdeviceCubit (package:parkways_onstreet_v2/src/presentation/bloc/checkdevice/checkdevice_cubit.dart:15:7)
#19     main.<anonymous closure> (package:parkways_onstreet_v2/main.dart:48:28)
#20     _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:736:36)
#21     _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:590:33)
#22     Provider.of (package:provider/src/provider.dart:303:37)
#23     ReadContext.read (package:provider/src/provider.dart:649:21)
#24     _BlocListenerBaseState.initState (package:flutter_bloc/src/bloc_listener.dart:158:36)
#25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5618:55)
#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463:5)
#27     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (236 frames)
#263    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340:16)
#264    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6904:36)
#265    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6916:32)
...     Normal element mounting (460 frames)
#725    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#732    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#739    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#746    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#753    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#760    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#767    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#774    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#781    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#788    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#795    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#802    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#809    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#816    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#823    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#830    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#837    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#844    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#851    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#858    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#865    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#872    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#879    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#886    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#893    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#900    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#907    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#914    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#921    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#928    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#935    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#942    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#949    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#956    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#963    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#970    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#977    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (27 frames)
#1004   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340:16)
#1005   Element.updateChild (package:flutter/src/widgets/framework.dart:3849:18)
#1006   _RawViewElement._updateChild (package:flutter/src/widgets/view.dart:291:16)
#1007   _RawViewElement.mount (package:flutter/src/widgets/view.dart:314:5)
...     Normal element mounting (7 frames)
#1014   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340:16)
#1015   Element.updateChild (package:flutter/src/widgets/framework.dart:3849:18)
#1016   RootElement._rebuild (package:flutter/src/widgets/binding.dart:1581:16)
#1017   RootElement.mount (package:flutter/src/widgets/binding.dart:1550:5)
#1018   RootWidget.attach.<anonymous closure> (package:flutter/src/widgets/binding.dart:1503:18)
#1019   BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2845:19)
#1020   RootWidget.attach (package:flutter/src/widgets/binding.dart:1502:13)
#1021   WidgetsBinding.attachToBuildOwner (package:flutter/src/widgets/binding.dart:1239:27)
#1022   WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1221:5)
#1023   WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:1207:7)
#1027   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════

D/eglCodecCommon(13515): setVertexArrayObject: set vao to 0 (0) 1 0
The Flutter DevTools debugger and profiler on Android SDK built for x86 is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:55110/KtwxuMFlODA=/
D/EGL_emulation(13515): eglMakeCurrent: 0xe126eb60: ver 2 0 (tinfo 0xc1776c60)
D/eglCodecCommon(13515): setVertexArrayObject: set vao to 0 (0) 1 0
E/flutter (13515): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Tried to read a provider that threw during the creation of its value.
E/flutter (13515): The exception occurred during the creation of type CheckdeviceCubit.
E/flutter (13515):
E/flutter (13515): ══╡ EXCEPTION CAUGHT BY PROVIDER ╞═══════════════════════════════
E/flutter (13515): The following RealmError was thrown:
E/flutter (13515): Realm error : Could not open librealm_dart.so. Tried:
E/flutter (13515): - "librealm_dart.so"
E/flutter (13515): Hint: Did you forget to add a dependency on the realm package?
E/flutter (13515):
E/flutter (13515): When the exception was thrown, this was the stack:
E/flutter (13515): #0      _openRealmLib.throwError (package:realm_dart/src/init.dart:71:5)
E/flutter (13515): #1      _openRealmLib (package:realm_dart/src/init.dart:84:29)
E/flutter (13515): #2      initRealm (package:realm_dart/src/init.dart:120:24)
E/flutter (13515): #3      _realmLib.<anonymous closure> (package:realm_dart/src/native/realm_core.dart:47:31)
E/flutter (13515): #4      _realmLib (package:realm_dart/src/native/realm_core.dart:55:2)
E/flutter (13515): #5      _realmLib (package:realm_dart/src/native/realm_core.dart)
E/flutter (13515): #6      new _RealmCore (package:realm_dart/src/native/realm_core.dart:104:5)
E/flutter (13515): #7      realmCore (package:realm_dart/src/native/realm_core.dart:81:24)
E/flutter (13515): #8      realmCore (package:realm_dart/src/native/realm_core.dart)
E/flutter (13515): #9      Configuration.defaultStoragePath (package:realm_dart/src/configuration.dart:85:14)
E/flutter (13515): #10     Configuration.defaultRealmPath (package:realm_dart/src/configuration.dart:95:47)
E/flutter (13515): #11     Configuration.defaultRealmPath (package:realm_dart/src/configuration.dart)
E/flutter (13515): #12     Configuration._defaultPath (package:realm_dart/src/configuration.dart:109:44)
E/flutter (13515): #13     new Configuration._ (package:realm_dart/src/configuration.dart:105:50)
E/flutter (13515): #14     new LocalConfiguration._ (package:realm_dart/src/configuration.dart:257:14)
E/flutter (13515): #15     Configuration.local (package:realm_dart/src/configuration.dart:154:26)
E/flutter (13515): #16     new RealmDBDevice._ (package:parkways_onstreet_v2/core/domain/database/checkdevice_db.dart:6:32)
E/flutter (13515): #17     new RealmDBDevice (package:parkways_onstreet_v2/core/domain/database/checkdevice_db.dart:13:58)
E/flutter (13515): #18     new CheckdeviceCubit (package:parkways_onstreet_v2/src/presentation/bloc/checkdevice/checkdevice_cubit.dart:15:7)
E/flutter (13515): #19     main.<anonymous closure> (package:parkways_onstreet_v2/main.dart:48:28)
E/flutter (13515): #20     _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:736:36)
E/flutter (13515): #21     _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:590:33)
E/flutter (13515): #22     Provider.of (package:provider/src/provider.dart:303:37)
E/flutter (13515): #23     ReadContext.read (package:provider/src/provider.dart:649:21)
E/flutter (13515): #24     _BlocListenerBaseState.initState (package:flutter_bloc/src/bloc_listener.dart:158:36)
E/flutter (13515): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5618:55)
E/flutter (13515): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463:5)
E/flutter (13515): #27     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
E/flutter (13515): ...     Normal element mounting (236 frames)
E/flutter (13515): #263    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340:16)
E/flutter (13515): #264    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6904:36)
E/flutter (13515): #265    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6916:32)
E/flutter (13515): ...     Normal element mounting (460 frames)
E/flutter (13515): #725    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
E/flutter (13515): ...     Normal element mounting (7 frames)
E/flutter (13515): #732    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
E/flutter (13515): ...     Normal element mounting (7 frames)
E/flutter (13515): #739    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
E/flutter (13515): ...     Normal element mounting (7 frames)
E/flutter (13515): #746    _NestedHookElement.mount (package:nested/nested.dart:187:11)
E/flutter (13515): ...     Normal element mounting (7 frames)
E/flutter (13515): #753    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
E/flutter (13515): ...     Normal element mounting (7 frames)
E/flutter (13515): #760    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
E/flutter (13515): ...     Normal element mounting (7 frames)
E/flutter (13515): #767    Single
Another exception was thrown: Bad state: Tried to read a provider that threw during the creation of its value.
```

**Comment by nirinchev** [comment]
It sounds like the .so file didn't get copied when building the application. Can you clarify which version did you upgrade from and per the error message, can you double check that you have `realm` as a dependency in your pubspec?

**Comment by AhmadFikriAS** [comment]
> It sounds like the .so file didn't get copied when building the application. Can you clarify which version did you upgrade from and per the error message, can you double check that you have `realm` as a dependency in your pubspec?

I am using version 2.3.0 in pubspec from previously upgrading to use 2.1.0
<img width="242" alt="image" src="https://github.com/realm/realm-dart/assets/43110908/4739542f-2201-40e5-93cc-4a4f5e8bbc0c">

**Comment by clchera** [comment]
Hi, I am having the same problem

**Comment by nielsenko** [comment]
@AhmadFikriAS & @clchera I have not been able to reproduce this.
- Could I ask you to check the `realm`, `realm_dart`, `realm_common`, and `realm_generator` entries in your `pubspec.lock` files and report back what versions you have?
- Are you both using windows?
- What emulator images are you using?

@AhmadFikriAS If you re-install your app on the emulator, do you still get this error?

@clchera Is it only on the emulator for you as well?

**Comment by AhmadFikriAS** [comment]
> @AhmadFikriAS & @clchera I have not been able to reproduce this.
> 
> * Could I ask you to check the `realm`, `realm_dart`, `realm_common`, and `realm_generator` entries in your `pubspec.lock` files and report back what versions you have? 
<img width="328" alt="error3" src="https://github.com/realm/realm-dart/assets/43110908/7cc7d738-d0e4-4996-a874-ef9006237585">

> * Are you both using windows? yes, i'm using windows version 11.
> * What emulator images are you using? Pixel 6a API 29
> 
> @AhmadFikriAS If you re-install your app on the emulator, do you still get this error? still same error

<img width="657" alt="error2" src="https://github.com/realm/realm-dart/assets/43110908/aa119185-11f2-4d6a-9173-23704e5caeb9">

**Comment by nielsenko** [comment]
@AhmadFikriAS What is the ABI-list for the _Pixel 6a API 29_ system image?

**Comment by AhmadFikriAS** [comment]
I'm on x86, and I've tried x86_64 and it works. Thank you for the answer, it really helped me. @nielsenko

**Comment by nielsenko** [comment]
For posterity I will elaborate a bit. 

Dart AoT compilation does [not](https://docs.flutter.dev/reference/supported-platforms) support x86. Hence flutter does not support it either in **release** mode. 

However, the flutter engine does come with a pre-build for x86, and hence if you use the Dart JiT compiler (as you do in **debug** mode), then you can actually run and debug your app on Android x86.

As is evident from this issue, it is possible to use an x86 system image when creating an Android emulator with Device Manager. At least as long as you stay below API-level 30, and forego the recommended images.

We could support this scenario (we did previously), as realm runs just fine on x86.  But doing so would increase the appbundle size on every app using realm, and never actually be used in production. 

So, as of realm-dart v2.3.0, you are required to update your Android emulator images to x86_64, or some arm variant, if you want to use them with Realm and Flutter.
