### ISSUE TITLE
0.3.0+beta/android.tar.gz. Error code: 404

### ISSUE THREAD

**Issue by Comanx** [realm/realm-dart#655]
```
Unhandled exception:
Exception: Error downloading Realm binaries from https://static.realm.io/downloads/dart/0.3.0+beta/android.tar.gz. Error code: 404
#0      InstallCommand.downloadAndExtractBinaries (package:realm/src/cli/install/install_command.dart:140:9)
<asynchronous suspension>
#1      InstallCommand.run (package:realm/src/cli/install/install_command.dart:205:5)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
pub finished with exit code 255

FAILURE: Build failed with an exception.
```

**Comment by blagoev** [comment]
@Comanx The just released 0.3.1+beta fixes this.
